{
  lib,
  buildPythonPackage,
  fetchPypi,
  pdm-backend,
  tqdm,
  hypothesis,
  pytest,
}:

buildPythonPackage rec {
  pname = "partial-json-parser";
  version = "0.2.1.post1";
  pyproject = true;

  src = fetchPypi {
    pname = "partial_json_parser";
    inherit version;
    hash = "sha256-4W+GStbixThNOpF5WYm0e4Uyk5cxh2oyO8qsiX32ixI=";
  };

  build-system = [ pdm-backend ];

  dependencies = [ ];
  pythonImportsCheck = [ "partial_json_parser" ];

  dev-dependencies = [
    hypothesis
    tqdm
    pytest
  ];

  meta = {
    description = "Parse partial JSON generated by LLM";
    homepage = "https://github.com/promplate/partial-json-parser";
    license = lib.licenses.mit;
  };
}
